target 'BetweenKit', :exclusive => true do
  pod "BetweenKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BetweenKit", :path => "../"
  pod 'Specta', :git => 'https://github.com/specta/specta.git', :tag => 'v0.3.0.beta1'
  pod 'OCMock', '~> 3.1.1'
  pod 'Expecta'
end
